### ISSUE TITLE
How did you find the SmartCam URIs?

### ISSUE THREAD

**Issue by unformatt** [airdrummingfool/SmartThings-SmartCam#2]
Sorry, would have emailed you but couldn't find your email.

How did you find URIs like `stw-cgi-rest/eventsources/videoanalysis`, etc? Are these documented somewhere?

**Comment by airdrummingfool** [comment]
No worries!

I found the URIs listed in [this post](https://community.smartthings.com/t/samsung-smartcam-snh-p6410bn-snh-e6440bn-and-snh-1011nd-www-digest-auth-tested-and-working/8801/50) (https://community.smartthings.com/t/samsung-smartcam-snh-p6410bn-snh-e6440bn-and-snh-1011nd-www-digest-auth-tested-and-working/8801/50) by user greko6 in the SmartThings Community forums.

**Comment by unformatt** [comment]
Awesome! During my search, I also found the direct streaming video URLs which can loaded in video players like VLC

```
rtsp://admin:[CAM_PASSWORD]@[CAM_IP]:554/onvif/profile1/media.smp -> 1080p MJPG
rtsp://admin:[CAM_PASSWORD]@[CAM_IP]:554/onvif/profile2/media.smp -> 360p 10fps MP4
rtsp://admin:[CAM_PASSWORD]@[CAM_IP]:554/onvif/profile3/media.smp -> 360p MJPG
rtsp://admin:[CAM_PASSWORD]@[CAM_IP]:554/onvif/profile4/media.smp -> 720p 15fps MP4
rtsp://admin:[CAM_PASSWORD]@[CAM_IP]:554/onvif/profile5/media.smp -> 1080p 30fps MP4
```
